### ISSUE TITLE
Upcoming changes to the App Store receipt signing certificate

### ISSUE THREAD

**Issue by TonyVie** [tikhop/TPInAppReceipt#105]
Hi !
From apple developer news: https://developer.apple.com/news/?id=ytb7qj0x

From what I understand, TPInAppReceipt will not be impacted. Can you confirm ?

**Comment by tikhop** [comment]
Hi @TonyVie, thanks for bringing it up. I'll take a look shortly.

**Comment by zsoltvarnai** [comment]
Hey @tikhop, I got to a similar conclusion, that this change might not effect TPInAppReceipt, but I don't think it's possible to actually test this before the deadline.

Do you have any update on your side if changes are required?

**Comment by tikhop** [comment]
@TonyVie @zsoltvarnai I did some research and I ended up with a conclusion that we are good and there is no need to do anything, since we only verify that the chain of trust for the container’s signature matches the Apple Inc. Root Certificate.

**Comment by zsoltvarnai** [comment]
That's great news, thank you!

**Comment by schmidan** [comment]
Sorry for bumping a closed issue. I checked the source and came here to verify my conclusion same as you guys.  

@tikhop could this information be made sticky or included in the readme?  
Because i guess more people might come here now to check: 
- https://developer.apple.com/documentation/technotes/tn3138-handling-app-store-receipt-signing-certificate-changes
