### ISSUE TITLE
Usage with SwiftyStoreKit?

### ISSUE THREAD

**Issue by teologov** [tikhop/TPInAppReceipt#26]
Hi! Thanks for your work on this library. I'd like to use it together with `SwiftyStoreKit`. 

Could you please add a very brief description of how to implement a validator which conforms to `ReceiptValidator` protocol from SwiftyStoreKit?

**Comment by tikhop** [comment]
@teologov Hi! I'm sorry, I've just noticed your comment here. I'll get back to you shortly with a brief description.

**Comment by teologov** [comment]
Hi @tikhop, no worries. I've already implemented the solution, and it's working fine. I can help to improve a readme and provide an example based on my code.

**Comment by tikhop** [comment]
@teologov Cool, thank you. Yeah, if you have a chance.

**Comment by teologov** [comment]
Ok, sure. I'll try to find some time and compose a working example this
weekend. I'll submit a PR once it's ready.

ср, 17 июл. 2019 г. в 13:05, Pavel Tikhoneko <notifications@github.com>:

**Comment by tikhop** [comment]
@teologov sounds good, let me know if you need any help.

**Comment by tikhop** [comment]
Hi @teologov, hope you are doing well. I've been working on my own project where I'm using `SwiftyStoreKit` and my lib. Basically, `SwiftyStoreKit` is just for working with store kit and when I'm done, I'm using my lib to verify and see if user can have an access to a specific content (in addition to our server validation, since apple highly recommended to validate receipt with apple on backend side. 

So, I'm thinking that we can combine those two libs in a way, that `SwiftyStoreKit` handle all work with storeKit and then you can get your receipt either by deserializing local receipt or load it from apple. Afterworlds, you can basically work with my (ours) `InAppReceipt` instance (it can be wrapped into some manager in order to handle receipt changes at one place and update `InAppReceipt ` object if needed). If you want to validate this object you can do it either by using own backend (simply by setting an endpoint url of your api method), locally using apple server or fully local validation (like it works now).

Let me know if you like an idea and i can provide some examples.

Thanks,
Pavel

**Comment by teologov** [comment]
Hi @tikhop, the last couple of weeks I was preparing my app to the App Store release, and due to the deadline, unfortunately, I haven't had a chance to work on any other tasks. Sorry about that.

I have implemented the working solution by building an extra layer, where I work with `SwiftyStoreKit` and `InAppReceipt` being used as a local validator. 

Please, see my solution [here](https://gist.github.com/teologov/0dcd284f79b7d9f7deda4c3af2f2c006).

It implements a basic local validation using your library. In particular, the `verifyReceipt()` method shows how I did it using `InAppReceipt.verifyHash()` because in the sandbox mode calling `InAppReceipt.verify()` throws an error.

If you could provide some examples with the BE verification, I think we could compose a good end to end example of purchases. 

Sorry again for being late in response.
