### ISSUE TITLE
rootCertificatePath is nil

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#41]
I just tried the latest build and rootCertificatePath seems nil and fails verification.

**Comment by tikhop** [comment]
@chrisvanbuskirk checking in a few...

**Comment by tikhop** [comment]
@chrisvanbuskirk fixed! Updating cocoapods now.

Thank you!

**Comment by IngmarStein** [comment]
It looks like the issue was only fixed for CocoaPods users. When integrating TPInAppReceipt with SwiftPM, the certificate file won't be found because the current SwiftPM release misses the feature of adding resources to package. Until [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) makes it into [Swift 5.3](https://forums.swift.org/t/se-0271-package-manager-resources/30730/73), it should probably be documented to add the cer file to the main bundle.

**Comment by tikhop** [comment]
@IngmarStein You

**Comment by tikhop** [comment]
@IngmarStein Just updated `Readme`. Thanks again for pointing this out.
