### ISSUE TITLE
Can be used with sandbox receipts?

### ISSUE THREAD

**Issue by Zasuk** [tikhop/TPInAppReceipt#42]
Hi,
I'm using it to validate sandbox receipts that i get with `SKReceiptRefreshRequest` but it fails...

`Error Domain=NSOSStatusErrorDomain Code=-25318 "“Mac App Store and iTunes Store Receipt Signing” certificate is not trusted" UserInfo={NSLocalizedDescription=“Mac App Store and iTunes Store Receipt Signing” certificate is not trusted, NSUnderlyingError=0x2830b7b10 {Error Domain=NSOSStatusErrorDomain Code=-25318 "Certificate 0 “Mac App Store and iTunes Store Receipt Signing” has errors: Unable to build chain to root (possible missing intermediate);" UserInfo={NSLocalizedDescription=Certificate 0 “Mac App Store and iTunes Store Receipt Signing” has errors: Unable to build chain to root (possible missing intermediate);}}}`

Can it be used with sandbox or not?

**Comment by tikhop** [comment]
Hi @Zasuk,

I will double check later today or, maximum, during the weekend. (@cupnoodle maybe you have some info related to the current issue?)

Thanks for you report!

**Comment by cupnoodle** [comment]
Hi @Zasuk , what is the platform of your app? is it macOS app or iOS app?

So far I have tested the signature validation on my own iOS app in both sandbox/production environment.

**Comment by Zasuk** [comment]
hi, i'm using it with iOS. i'll email you the base64 data.
you need the value returned by the `var base64` in `InAppReceipt` , right?

**Comment by cupnoodle** [comment]
Hi @Zasuk , Ah I see, yes the data in `var base64` in `InAppReceipt`.

**Comment by cupnoodle** [comment]
Heya @Zasuk , I have found the issue, its because I didn't include WWDR (Worldwide developer certificate) in the chain of trust between iTunes certificate and Apple Root certificate.

I have submitted a pull request to fix this, but if you are in a hurry, you can modify the `Validation.swift` of this library, and add `worldwideDevCertSec` in the array in Line 169.

<img width="1112" alt="Screenshot 2019-12-08 at 11 34 38 PM" src="https://user-images.githubusercontent.com/3954625/70391792-f5471a80-1a13-11ea-9168-37de2e4b2ac6.png">

If you are using Cocoapods, after modifying the file, press "option + command + shift + K" to clean the build folder and build again.

Sorry for the inconvenience caused, hope this helps!

**Comment by tikhop** [comment]
@Zasuk, @cupnoodle I will accept PR in a bit and update cocoapods as well.

Thanks to both of you! 
P

**Comment by tikhop** [comment]
@Zasuk, @cupnoodle Just released a new version.

Thanks again.
P

**Comment by cupnoodle** [comment]
Thanks @tikhop  and @Zasuk !

**Comment by Zasuk** [comment]
awesome!! thank you guys

**Comment by everwanna** [comment]
Thank you @Zasuk @tikhop @cupnoodle
