### ISSUE TITLE
"" is damaged and can't be opened. Delete "" and download it again from the App Store.

### ISSUE THREAD

**Issue by mikeumus** [tikhop/TPInAppReceipt#66]
... "In-App Purchase Receipt Validation" ... 🤔

Does this mean the user has to buy something in the app for validation to work? 

- What about when a user first downloads the app from the App Store?
- Can freshly installed apps be validated as well? 
- What stops someone from who bought the app from MAS to then upload it to a torrent network?

Thanks @tikhop 🙇🏻‍♂️

**Comment by tikhop** [comment]
Hi @mikeumus,

In order to validate a receipt you must have a receipt ready. Usually, you validate a local receipt for your app, but there is nothing wrong to validate a receipt from another device and app. To get a local receipt you must have at least one purchase within an app.

_What about when a user first downloads the app from the App Store?_
If you try to retrieve a local receipt you will get an error.

_Can freshly installed apps be validated as well?_
Freshly installed app doesn't have a receipt, therefore, nothing to validate.

_What stops someone from who bought the app from MAS to then upload it to a torrent network?_
Nothing can stop someone to upload some binary to a torrent network... 

Best,
P

**Comment by mikeumus** [comment]
Thanks for the informative answer @tikhop 👍

**Comment by tikhop** [comment]
@mikeumus you are welcome. ✌️
